import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/common/navbar";
import Footer from "@/components/common/footer";
import { Toaster } from "sonner";
import AuthProvider from "@/providers/auth-provider";
import CartContextProvider from "@/providers/cart-provider";
import WishlistProvider from "@/providers/wishlist-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <CartContextProvider>
            <WishlistProvider>
              <Navbar />
              {children}
              <Toaster position="top-center" richColors />
              <Footer />
            </WishlistProvider>
          </CartContextProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
